---
- name: Converge
  hosts: all
  gather_facts: yes
  # pre_tasks:
  #   - debug:
  #       var: ansible_facts
  roles:
    - role: devopsworks.auditd
      auditd_local_rulesets: ["38-anssi","39-neo23x0"]
      auditd_source_rulesets: ["30-stig","41-containers"]
      auditd_custom_rules:
      - "-a exit,always -F arch=b64 -S unlink -S rmdir -S rename -k fschange"
      - "-a exit,always -F arch=b64 -S creat -S open -S openat -F exit=-EACCES -k fschange"
      - "-a exit,always -F arch=b64 -S truncate -S ftruncate -F exit=-EACCES -k fschange"
      __sut: true