---
dependency:
  name: galaxy
driver:
  name: docker
platforms:

  - name: systemd-debian-latest
    image: jrei/systemd-debian:latest
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
verifier:
  name: ansible
